definitions:
  api.ApiError:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/api.Data'
      status:
        type: string
    type: object
  api.Data:
    properties:
      error:
        type: string
    type: object
  service.InitializeAccountService:
    properties:
      custId:
        type: string
    required:
    - custId
    type: object
info:
  contact: {}
paths:
  /v1/init:
    post:
      consumes:
      - application/json
      parameters:
      - description: Data init
        in: body
        name: menus
        required: true
        schema:
          $ref: '#/definitions/service.InitializeAccountService'
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ApiError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/api.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ApiError'
      summary: API untuk Inisialisasi akun baru
      tags:
      - Menu
swagger: "2.0"
